### ISSUE TITLE
Удаление пользователей сломано

### ISSUE THREAD

**Issue by solonrome** [Grisha-OK/Github-for-me-#10]
Обстоятельства:
- создал базу скриптом Data_base_extras
- создал нового пользователя
- попытался удалить одного из пользователей

5
Ведите номер счета для удаления
44578130
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/suser/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/suser/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/suser/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/suser/Documents/Gri/Github-for-me-/Swiss_bank.py", line 111, in <module>
    delete_user()          #то вызывается функцыя удоления пользователя
  File "/home/suser/Documents/Gri/Github-for-me-/Swiss_bank.py", line 64, in delete_user
    q = data_base[i]            #приравневаем q к атдельно взятм элиментам, как в конструкции < for q in data_base: >
IndexError: list index out of range

**Comment by solonrome** [comment]
Возможное решение - вынести удаление элемента списка из цикла наружу.
